
CREATE TABLE MODALIDADES (
    ID_MODALIDAD INT PRIMARY KEY,
    MODALIDAD VARCHAR(50)
);
CREATE TABLE ENFOQUES (
    ID_ENFOQUES INT PRIMARY KEY,
    ENFOQUES VARCHAR(100)
);

CREATE TABLE CATEGORIA_DE_DISCAPACIDAD (
    ID_CATEGORIA INT PRIMARY KEY,
    CATEGORIA VARCHAR(50)
);

CREATE TABLE PERSONA_MODALIDAD (
    ID_PERSONA INT,
    ID_MODALIDAD INT,
    PRIMARY KEY (ID_PERSONA, ID_MODALIDAD),
    FOREIGN KEY (ID_MODALIDAD) REFERENCES MODALIDADES(ID_MODALIDAD)
);

CREATE TABLE PERSONA_ENFOQUE (
    ID_PERSONA INT,
    ID_ENFOQUE INT,
    PRIMARY KEY (ID_PERSONA, ID_ENFOQUE),
    FOREIGN KEY (ID_ENFOQUE) REFERENCES ENFOQUES(ID_ENFOQUES)
);

CREATE TABLE PERSONA_CATEGORIA (
    ID_PERSONA INT,
    ID_CATEGORIA INT,
    PRIMARY KEY (ID_PERSONA, ID_CATEGORIA),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_DE_DISCAPACIDAD(ID_CATEGORIA)
);

INSERT INTO MODALIDADES (ID_MODALIDAD, MODALIDAD) VALUES (1, 'Telemedicina');
SELECT * FROM MODALIDADES;

-- 6. TABLA PRINCIPAL DE PERSONAS

CREATE TABLE PERSONAS (
    ID_PERSONA INT PRIMARY KEY,
    DEPARTAMENTO VARCHAR(50),
    MUNICIPIO VARCHAR(50),
    GENERO CHAR(1),
    EDAD INT,
    CURSO_DE_VIDA VARCHAR(30),
    DIAGNOSTICO TEXT,
    CODIGO_CIE10 TEXT
);

--