CREATE TABLE `PERSONA` (
  `ID_PERSONA` int PRIMARY KEY,
  `DEPARTAMENTO` varchar(255),
  `MUNICIPIO` varchar(255),
  `GENERO` char,
  `EDAD` varchar(255),
  `CURSO_VIDA` varchar(255)
);

CREATE TABLE `DIAGNOSTICO` (
  `ID_DIAGNOSTICO` int PRIMARY KEY,
  `DIAGNOSTICO` text,
  `CODIGO_CIE10` varchar(255)
);

CREATE TABLE `PERSONA_DIAGNOSTICO` (
  `ID_PERSONA` int,
  `ID_DIAGNOSTICO` int
);

CREATE TABLE `MODALIDAD` (
  `ID_MODALIDAD` int PRIMARY KEY,
  `MODALIDAD` varchar(255)
);

CREATE TABLE `PERSONA_MODALIDAD` (
  `ID_PERSONA` int,
  `ID_MODALIDAD` int
);

CREATE TABLE `CATEGORIA_DISCAPACIDAD` (
  `ID_CATEGORIA` int PRIMARY KEY,
  `CATEGORIA` varchar(255)
);

CREATE TABLE `PERSONA_CATEGORIA` (
  `ID_PERSONA` int,
  `ID_CATEGORIA` int
);

CREATE TABLE `ENFOQUE_DIFERENCIAL` (
  `ID_ENFOQUE` int PRIMARY KEY,
  `ENFOQUE` varchar(255)
);

CREATE TABLE `PERSONA_ENFOQUE` (
  `ID_PERSONA` int,
  `ID_ENFOQUE` int
);

ALTER TABLE `PERSONA_DIAGNOSTICO` ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID_PERSONA`);

ALTER TABLE `PERSONA_DIAGNOSTICO` ADD FOREIGN KEY (`ID_DIAGNOSTICO`) REFERENCES `DIAGNOSTICO` (`ID_DIAGNOSTICO`);

ALTER TABLE `PERSONA_MODALIDAD` ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID_PERSONA`);

ALTER TABLE `PERSONA_MODALIDAD` ADD FOREIGN KEY (`ID_MODALIDAD`) REFERENCES `MODALIDAD` (`ID_MODALIDAD`);

ALTER TABLE `PERSONA_CATEGORIA` ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID_PERSONA`);

ALTER TABLE `PERSONA_CATEGORIA` ADD FOREIGN KEY (`ID_CATEGORIA`) REFERENCES `CATEGORIA_DISCAPACIDAD` (`ID_CATEGORIA`);

ALTER TABLE `PERSONA_ENFOQUE` ADD FOREIGN KEY (`ID_PERSONA`) REFERENCES `PERSONA` (`ID_PERSONA`);

ALTER TABLE `PERSONA_ENFOQUE` ADD FOREIGN KEY (`ID_ENFOQUE`) REFERENCES `ENFOQUE_DIFERENCIAL` (`ID_ENFOQUE`);
